GET http://localhost:3000/posts
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZWRsX3Rlc3Rlcl8zIiwiaWF0IjoxNjk3NDM0NzMxLCJleHAiOjE2OTc0MzQ3NDZ9.3FkqdI9YrbBhBEpQnH-3y4ZhUMP_6pUFogYRvxR1EqQ
###

POST http://localhost:4000/token 
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZWRsX3Rlc3Rlcl8zIiwiaWF0IjoxNjk3NDM0Njk3fQ.Ev_SZf7aHM7QvnIBxLOwxY3AqmQPObO_Frfuzsp9ISc"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZWRsX3Rlc3Rlcl8zIiwiaWF0IjoxNjk3NDM0Njk3fQ.Ev_SZf7aHM7QvnIBxLOwxY3AqmQPObO_Frfuzsp9ISc"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "edl_tester_3",
    "password": "password"
}


###

GET http://localhost:4000/users


###

POST http://localhost:4000/users
Content-Type: application/json

{
    "username": "edl_tester_3",
    "password": "password"
}