GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFuaW5lIiwiaWF0IjoxNjk3Mjk4MzQ4fQ.y_KXJsiUC_AG-SPlMr5qPbaVqbcp25QJFJaH3QBTYTY


###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Janine"
}
